#!/bin/bash -login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=48
#PBS -N gordon_merged_core_microbiome_CDA_report
#PBS -A d411-training

#Load python modules
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# activate the virtual environment
echo "activating virtual environment"
source activate qiime1

# CDA on merged gordon core microbiome
echo "carrying out CDA on merged gordon core microbiome"

time core_diversity_analyses.py -i ~/bioc3301/combi_analysis/gordon_merged_combi_core_otu_table/core_table_50.biom -o ~/bioc3301/combi_analysis/GORDON_MERGED_CORE_MICROBIOME_CDA -m ~/bioc3301/combi_analysis/yrs_merged_map.tsv -e 26786 -t ~/SILVA_128_QIIME_release/trees/97/97_otus.tre --recover_from_failure -a -O 24

#deactivating virtual environment
source deactivate
