#!/bin/bash -login
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=48
#PBS -N gordon_1718_core_microbiome_CDA_report
#PBS -A d411-training

#Load python modules
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# activate the virtual environment
echo "activating virtual environment"
source activate qiime1

# CDA on 17/18 gordon core microbiome
echo "carrying out CDA on 17/18 gordon core microbiome"

time core_diversity_analyses.py -i ~/bioc3301/1718_analysis/1718_gordon_core_otu_table/core_table_50.biom -o ~/bioc3301/1718_analysis/1718_GORDON_CORE_MICROBIOME_CDA -m ~/bioc3301/combi_analysis/yrs_merged_map.tsv -e 26717 -t ~/SILVA_128_QIIME_release/trees/97/97_otus.tre --recover_from_failure -a -O 24

#deactivating virtual environment
source deactivate
