#!/bin/bash -login
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=16
#PBS -N identify_1718_core_microbiome_report
#PBS -A d411-training

#Load python modules
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# activate the virtual environment
echo "activating virtual environment"
source activate qiime1

# identify core microbiome 17/18
echo "identifying 17/18 core microbiome"
time compute_core_microbiome.py -i ~/bioc3301/1718_analysis/1718_gordon_merged_otu_table.biom -o ~/bioc3301/1718_analysis/1718_gordon_core_otu_table

#deactivating virtual environment
source deactivate
