#!/bin/bash -login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=8
#PBS -N 1718_anosim_test_report
#PBS -A d411-training

#Load python modules
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# activate the virtual environment
echo "activating virtual environment"
source activate qiime1

#Anosim test on weighted unifraq - year
echo "performing anosim test"
time compare_categories.py -i ~/bioc3301/1718_analysis/1718_GORDON_CORE_MICROBIOME_CDA/bdiv_even26717/weighted_unifrac_dm.txt -m ~/bioc3301/combi_analysis/yrs_merged_map.tsv -c Year --method anosim -o ~/bioc3301/1718_analysis/1718_stats_tests/anosim_year_WUF

#Anosim test on unweighted unifraq - year
echo "performing anosim test"
time compare_categories.py -i ~/bioc3301/1718_analysis/1718_GORDON_CORE_MICROBIOME_CDA/bdiv_even26717/unweighted_unifrac_dm.txt -m ~/bioc3301/combi_analysis/yrs_merged_map.tsv -c Year --method anosim -o ~/bioc3301/1718_analysis/1718_stats_tests/anosim_year_UWUF

# deactivate virtual environment
source deactivate
