#!/bin/bash -login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=16
#PBS -N create_upgma_report
#PBS -A d411-training

#Load python modules
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# activate the virtual environment
echo "activating virtual environment"
source activate qiime1

# create UPGMA tree
echo "creating UPGMA tree"
time upgma_cluster.py -i ~/bioc3301/combi_analysis/GORDON_MERGED_CORE_MICROBIOME_CDA/bdiv_even26786/weighted_unifrac_dm.txt -o ~/weighted_beta_div_cluster.tre

# deactivate virtual environment
source deactivate
