#!/bin/bash -login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=48
#PBS -N core_diversity_analyses_report
#PBS -A d411-training

#Load python modules
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# activate the virtual environment
echo "activating virtual environment"
source activate qiime1

#Core Diversity Analysis
echo "carrying out CDA"

core_diversity_analyses.py -i ~/bioc3301/2018_02_smb/silva_otus/otu_table.biom -o ~/bioc3301/2018_02_smb/silva_core_analysis -m ~/bioc3301/2018_02_smb/map.tsv -e 627 -t ~/SILVA_128_QIIME_release/trees/97/97_otus.tre --recover_from_failure -a -O 24

#deactivating virtual environment
source deactivate
