#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N paired_ends_report
#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv"
source activate qiime1

# join paired ends
echo "joining paired ends"

time join_paired_ends.py -m SeqPrep -b ~/bioc3301/2018_02_smb/Index.fastq.gz -f ~/bioc3301/2018_02_smb/Read1.fastq.gz -r ~/bioc3301/2018_02_smb/Read2.fastq.gz -o ~/bioc3301/2018_02_smb/joined_ends

# source deactivate
source deactivate
