#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=32
#PBS -N picking_otu_silva_tracker
#PBS -A d411-training

module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv"
source activate qiime1

# pick OTUs
echo "picking OTUs"

time pick_closed_reference_otus.py -i ~/bioc3301/2018_02_smb/demultiplexed_q20/seqs.fna -o ~/bioc3301/2018_02_smb/silva_otus -r ~/SILVA_128_QIIME_release/rep_set/rep_set_16S_only/97/97_otus_16S.fasta -t ~/SILVA_128_QIIME_release/taxonomy/16S_only/97/majority_taxonomy_all_levels.txt -a -O 16

# source deactivate
source deactivate
