#!/bin/bash -login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=48
#PBS -N merged_core_diversity_analyses_report
#PBS -A d411-training

#Load python modules
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# activate the virtual environment
echo "activating virtual environment"
source activate qiime1

# merged Core Diversity Analysis
echo "carrying out merged CDA"

core_diversity_analyses.py -i ~/bioc3301/combi_analysis/merged_otu_table.biom -o ~/bioc3301/combi_analysis/MERGED_CORE_DIVERSITY_ANALYSIS -m ~/bioc3301/combi_analysis/yrs_merged_map.tsv -e 627 -t ~/SILVA_128_QIIME_release/trees/97/97_otus.tre --recover_from_failure -a -O 24

#deactivating virtual environment
source deactivate
