#!/bin/bash -login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=16
#PBS -N merge_otus_report
#PBS -A d411-training

#Load python modules
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# activate the virtual environment
echo "activating virtual environment"
source activate qiime1

# merging OTU tables
echo "merging 16, 17 and 18 yr OTU tables"

time merge_otu_tables.py -i 16_otu_table.biom,17_otu_table.biom,18_otu_table.biom -o ~/merged_otu_table.biom

# deactivate virtual environment
source deactivate
~                     
