#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N merging_maps_report
#PBS -A d411-training

module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv"
source activate qiime1

# merge all maps
echo "merging maps"

time merge_mapping_files.py -m 18_map.tsv,17_map.tsv,16_map.tsv -o merged_map.tsv

# source deactivate
source deactivate
