#!/bin/bash -login
#PBS -l walltime=00:10:00
#PBS -l select=1:ncpus=2
#PBS -N remove_non_gordon_report
#PBS -A d411-training

#Load python modules
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# activate the virtual environment
echo "activating virtual environment"
source activate qiime1

# remove non-gordon-square samples
echo "removing samples"

time filter_samples_from_otu_table.py -i ~/bioc3301/combi_analysis/merged_otu_table.biom -o ~/bioc3301/combi_analysis/gordon_merged_otu_table.biom --sample_id_fp ~/bioc3301/combi_analysis/ids.txt --negate_sample_id_fp

#deactivating virtual environment
source deactivate
